### ISSUE TITLE
Unable to run Odoo Shell

### ISSUE THREAD

**Issue by sunnysideupcom** [bitnami/bitnami-docker-odoo#62]
**Description**

I need to run Odoo shell (running Odoo queries from terminal), it is possible with regular Odoo installation but not with Bitnami container.

**Steps to reproduce the issue:**

1. run "odoo-bin shell -d database_name"

**Describe the results you received:**

2019-05-15 11:31:08,840 3827 INFO ? odoo: Odoo version 12.0-20190318 
2019-05-15 11:31:08,840 3827 INFO ? odoo: addons paths: ['/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/.local/addons/12.0', '/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons'] 
2019-05-15 11:31:08,841 3827 INFO ? odoo: database: default@default:default 
Warn: Can't find .pfb for face 'Times-Roman'
2019-05-15 11:31:09,005 3827 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-05-15 11:31:09,186 3827 INFO ? odoo.service.server: Initiating shutdown 
2019-05-15 11:31:09,187 3827 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-05-15 11:31:09,189 3827 INFO ? odoo.sql_db: Connection to the database failed 
Traceback (most recent call last):
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'database_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OdooSource/odoo-12.0.20190318-1/apps/odoo/bin/odoo-bin", line 9, in <module>
    odoo.cli.main()
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/cli/shell.py", line 125, in run
    self.shell(config['db_name'])
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/cli/shell.py", line 111, in shell
    registry = odoo.registry(dbname)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 74, in new
    registry.init(db_name)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 142, in init
    with closing(self.cursor()) as cr:
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 470, in cursor
    return self._db.cursor()
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/sql_db.py", line 657, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/sql_db.py", line 171, in __init__
    self._cnx = pool.borrow(dsn)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/sql_db.py", line 540, in _locked
    return fun(self, *args, **kwargs)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/sql_db.py", line 608, in borrow
    **connection_info)
  File "/home/ubuntu/OdooSource/odoo-12.0.20190318-1/python/lib/python3.7/site-packages/psycopg2-2.7.3.1-py3.7-linux-x86_64.egg/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @sunnysideupcom ,
Could you detail your installation process and settings?
Are you running Odoo Shell on your local machine?
Also, does you database `database_name` exists?

**Comment by sunnysideupcom** [comment]
Yes, everything was correct.
I have fixed the issue myself, found a workaround.
I have given all rights for postgresql by changing it from md5 to trust.
