### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/odoo/tmp/pids/odoo.pid\n

### ISSUE THREAD

**Issue by dugiahuy** [bitnami/bitnami-docker-odoo#76]
**Description**

I had successfull installed Odoo, included database (pg), persistent volume. I ran k8s with preemtible node in GCP. So its has a little downtime at least 5min/ per day. When preemtible node down or Odoo's pod deleted, its couldn't restart. Odoo's pod CrashLoopBack forever.

**Steps to reproduce the issue:**

1. Successfully Install Odoo 
2. Delete pod that running Odoo

**Describe the results you received:**

```
Welcome to the Bitnami odoo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
nami    INFO  Initializing odoo
odoo    INFO
odoo    INFO  ########################################################################
odoo    INFO   Installation parameters for odoo:
odoo    INFO     Persisted data and properties have been restored.
odoo    INFO     Any input specified will not take effect.
odoo    INFO   This installation requires no credentials.
odoo    INFO  ########################################################################
odoo    INFO
nami    INFO  odoo successfully initialized
INFO  ==> Starting odoo...
nami    ERROR Unable to start com.bitnami.odoo: Traceback (most recent call last):
  File "odoo-server", line 9, in <module>
    odoo.cli.main()
  File "/opt/bitnami/odoo/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/opt/bitnami/odoo/odoo/cli/server.py", line 176, in run
    main(args)
  File "/opt/bitnami/odoo/odoo/cli/server.py", line 169, in main
    setup_pid_file()
  File "/opt/bitnami/odoo/odoo/cli/server.py", line 84, in setup_pid_file
    with open(config['pidfile'], 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/odoo/tmp/pids/odoo.pid\nhttps://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922'
```

**Version**

- Output of `kubernetes version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

It seems that there's something incorrect in the path

`/opt/bitnami/odoo/tmp/pids/odoo.pid\nhttps://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922`

Do you have access to the configuration file?

**Comment by dugiahuy** [comment]
Hi @javsalgar 

I don't do anything with the configuration file. I just setting the environment for helm chart template and install it.
I see the helm template define only one PVC for path `/var/lib/odoo`. Where is the path of the configuration file?

Thank you for your support

**Comment by masterkain** [comment]
I have the same issue, upon restarting, how to fix?

**Comment by carrodher** [comment]
Hi, please can you provide more information?

- Are you using this image in a docker-compose or Helm chart? Did you modify the `docker-compose.yaml` or something in the chart? Can you share those changes?
- What version of the image are you using?
- Can you share any logs?
Thanks

**Comment by masterkain** [comment]
helm 2, eks 1.14

I deploy via Helm Operator, here's the full HelmRelease.

so what happens is that I installed odoo with success, let the company work with it for few hours, then they asked me to install an addon, did, killed the odoo pod, let it restart, it does not restart.

it takes a LONG time in initializing odoo, then it says something about pid not found.

we tried the same thing about a month ago with a different release and got pretty much the same result.

```
│ Welcome to the Bitnami odoo container                                                                                                                                                                                                                │
│ Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo                                                                                                                                                              │
│ Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues                                                                                                                                                          │
│                                                                                                                                                                                                                                                      │
│ nami    INFO  Initializing odoo

GIANT PAUSE

│ nami    ERROR Unable to start com.bitnami.odoo: Traceback (most recent call last):                                                                                                                                                                   │
│   File "odoo-server", line 9, in <module>                                                                                                                                                                                                            │
│     odoo.cli.main()                                                                                                                                                                                                                                  │
│   File "/opt/bitnami/odoo/odoo/cli/command.py", line 60, in main                                                                                                                                                                                     │
│     o.run(args)                                                                                                                                                                                                                                      │
│   File "/opt/bitnami/odoo/odoo/cli/server.py", line 176, in run                                                                                                                                                                                      │
│     main(args)                                                                                                                                                                                                                                       │
│   File "/opt/bitnami/odoo/odoo/cli/server.py", line 169, in main                                                                                                                                                                                     │
│     setup_pid_file()                                                                                                                                                                                                                                 │
│   File "/opt/bitnami/odoo/odoo/cli/server.py", line 84, in setup_pid_file                                                                                                                                                                            │
│     with open(config['pidfile'], 'w') as fd:                                                                                                                                                                                                         │
│ FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/odoo/tmp/pids/odoo.pid\nhttps://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922'

```

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: odoo
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  # resetValues: true
  releaseName: odoo
  chart:
    repository: https://charts.bitnami.com
    name: odoo
    version: 12.0.3
  containers:
  # - env:
  #   - name: NAMI_DEBUG
  #     value: --log-level=trace8
  values:
    postgresql:
      enabled: true
      postgresqlPassword: xxxxxx
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 20Gi
    odooUsername: xxxx
    odooPassword: xxxx
    odooEmail:  xxxx
    smtpHost: email-smtp.eu-west-1.amazonaws.com
    smtpPort: 587
    smtpUser: xxxxx
    smtpPassword: xxxxxx
    smtpProtocol: tls
    service:
      type: ClusterIP
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          proxy_hide_header l5d-remote-ip;
          proxy_hide_header l5d-server-id;
      hosts:
        - name: odoo.mydomain.it
    persistence:
      enabled: true
      storageClass: efs
      accessMode: ReadWriteMany
      size: 30Gi

```

**Comment by masterkain** [comment]
I believe I found the issue.

in the config file /opt/bitnami/odoo/odoo-server.conf

there is:

```
pidfile = /opt/bitnami/odoo/tmp/pids/odoo.pid
 https://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922
limit_time_cpu = 90
```

**Comment by carrodher** [comment]
Yes, it should be a comment. Installing it from scratch:
```bash
$ helm install bitnami/odoo

$ kubectl get pods
NAME                                                  READY   STATUS             RESTARTS   AGE
undercooked-marmot-odoo-68757784c7-5w8rw              1/1     Running            0          4m29s
undercooked-marmot-postgresql-0                       1/1     Running            0          4m30s

$ kubectl exec -it undercooked-marmot-odoo-68757784c7-5w8rw cat /opt/bitnami/odoo/odoo-server.conf
[options]
addons_path = /opt/bitnami/odoo/odoo/addons
admin_passwd = hGHwS0VQ4a
csv_internal_sep = ,
data_dir = /opt/bitnami/odoo/data
db_host = undercooked-marmot-postgresql
db_maxconn = 64
db_name = bitnami_odoo
db_password = ngWbqhgD
db_port = 5432
db_template = template1
db_user = bn_odoo
dbfilter = .*
debug_mode = False
demo = {}
dev_mode = False
email_from = user@example.com
log_level = info
logfile = /opt/bitnami/odoo/logs/odoo-server.log
pidfile = /opt/bitnami/odoo/tmp/pids/odoo.pid
; https://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922
limit_time_cpu = 90
limit_time_real = 150
limit_memory_soft = 3200000000
limit_memory_hard = 3200000000
;smtp_password =
;smtp_port =
;smtp_server =
;smtp_ssl =
;smtp_user =
```

So, what happens if you do the same process but without installing the addon? I mean, only the restart

**Comment by masterkain** [comment]
I found out there's not even need of a restart, right off the bat the extra line is there after the very first boot. 
![Screenshot 2019-12-18 at 04 40 42](https://user-images.githubusercontent.com/12844/71053969-92aaf880-2150-11ea-9f1e-ba2122829e5b.png)

**Comment by carrodher** [comment]
It's really weird, I am trying to reproduce the issue but I am not able.
I have the same deployment running for 4 days and a new one:
```bash
$ kubectl get pods
NAME                                       READY   STATUS    RESTARTS   AGE
odoo-1576750573-d588cbf7f-jvkzw            1/1     Running   0          7m20s
odoo-1576750573-postgresql-0               1/1     Running   0          7m20s
undercooked-marmot-odoo-68757784c7-5w8rw   1/1     Running   0          2d19h
undercooked-marmot-postgresql-0            1/1     Running   0          2d19h
```
in both cases, the line is commented:
```bash
$ kubectl exec -it undercooked-marmot-odoo-68757784c7-5w8rw cat /opt/bitnami/odoo/odoo-server.conf | grep 'https://www.odoo.com/forum'
; https://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922

$ kubectl exec -it odoo-1576750573-d588cbf7f-jvkzw cat /opt/bitnami/odoo/odoo-server.conf | grep 'https://www.odoo.com/forum'
; https://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922
```

What actions/commands are you used to do in this odoo deployment? I will try to reproduce it. In the same way, are you using the same volume every time?

**Comment by masterkain** [comment]
I'm not doing anything fancy, however it happened again: I edited the config file on the fly and waited for odoo to start up.
it lasted 4 days then the problem came back again (probably after an automated pod reboot, I'm not sure), line with no comment in config file, so I think it must be some startup script.

**Comment by carrodher** [comment]
I think I found the issue, by default the `odoo-server.conf` contains, among others, the following lines:
```
logfile = /opt/bitnami/odoo/logs/odoo-server.log
pidfile = /opt/bitnami/odoo/tmp/pids/odoo.pid
; https://www.odoo.com/forum/help-1/question/cpu-time-limit-exceeded-how-to-solve-it-87922
limit_time_cpu = 90
limit_time_real = 150
limit_memory_soft = 3200000000
limit_memory_hard = 3200000000
;smtp_password =
;smtp_port =
;smtp_server =
;smtp_ssl =
;smtp_user =
```
we have a logic in the image to configure SMTP removing the `;` and setting the correct values for those variables. The problem is that this logic is not working as expected and it is also removing the `;` from the `; https://...` comment. So one of the conditions to reproduce the issue is to set the SMTP parameters in the chart.

I just improved the logic in the image, once the new image was published in DockerHub I will update the chart to use this new revision of the image.

**Comment by carrodher** [comment]
The image version including the fix for this issue was released yesterday: https://github.com/bitnami/bitnami-docker-odoo/commit/90bae1b441dafd9108f569ab50a5fb93e86b7d2c
(same changes were also applied to other versions and distros)

In the same way, this is the PR including this image (or a newer one) in the chart: https://github.com/helm/charts/pull/19760

Once the Helm CI/CD finished and the new chart version (`12.0.5`) appears in the stable repository (`helm repo update` needed) you should be able to use the chart without issues. Please, let us know if the issue persists with the new version

**Comment by masterkain** [comment]
thanks @carrodher for that, I'm trying deploying 12.0.5 to test the fix, however the extremely slow startup issue is still there.

there's now a pod that has loaded the newer image, however it's 42 minutes and counting showing only `Initializing odoo`

```
│Events:
│  Type     Reason     Age                    From                                                   Message
│  ----     ------     ----                   ----                                                   -------
│  Normal   Scheduled  43m                    default-scheduler                                      Successfully assigned prod/odoo-7d56dbc76b-ptgb2 to ip-192-168-123-99.eu-west-1.compute.internal
│  Normal   Pulled     43m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Container image "gcr.io/linkerd-io/proxy-init:v1.1.0" already present on machine
│  Normal   Created    43m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Created container linkerd-init
│  Normal   Started    43m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Started container linkerd-init
│  Normal   Pulling    43m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Pulling image "docker.io/bitnami/odoo:12.0.20191215-debian-9-r9"
│  Normal   Pulled     42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Successfully pulled image "docker.io/bitnami/odoo:12.0.20191215-debian-9-r9"
│  Normal   Created    42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Created container odoo
│  Normal   Started    42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Started container odoo
│  Normal   Pulled     42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Container image "gcr.io/linkerd-io/proxy:stable-2.6.0" already present on machine
│  Normal   Created    42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Created container linkerd-proxy
│  Normal   Started    42m                    kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Started container linkerd-proxy
│  Warning  Unhealthy  3m17s (x228 over 42m)  kubelet, ip-192-168-123-99.eu-west-1.compute.internal  Readiness probe failed: HTTP probe failed with statuscode: 502
```

what can I do to assist for this issue?

**Comment by masterkain** [comment]
I checked the `odoo-postgresql-0` pod logs during startup and is filled with

```
│ 2019-12-24 14:18:21.065 GMT [27661] STATEMENT:  SELECT latest_version FROM ir_module_module WHERE name='base'
│ 2019-12-24 14:19:00.453 GMT [27661] ERROR:  relation "ir_module_module" does not exist at character 28
│ 2019-12-24 14:19:00.453 GMT [27661] STATEMENT:  SELECT latest_version FROM ir_module_module WHERE name='base'
│ 2019-12-24 14:19:22.129 GMT [27661] ERROR:  relation "ir_module_module" does not exist at character 28
│ 2019-12-24 14:19:22.129 GMT [27661] STATEMENT:  SELECT latest_version FROM ir_module_module WHERE name='base'
```

**Comment by masterkain** [comment]
after 1hr+ it started, some logs:

```
2019-12-24 15:21:10,789 58 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database bitnami_odoo.
│ 2019-12-24 15:21:17,706 58 INFO ? werkzeug: 127.0.0.1 - - [24/Dec/2019 15:21:17] "GET / HTTP/1.1" 200 - 1 0.003 0.044
│ 2019-12-24 15:21:27,710 58 INFO ? werkzeug: 127.0.0.1 - - [24/Dec/2019 15:21:27] "GET / HTTP/1.1" 200 - 1 0.003 0.048
│ 2019-12-24 15:21:30,784 58 INFO ? werkzeug: 127.0.0.1 - - [24/Dec/2019 15:21:30] "GET / HTTP/1.1" 200 - 1 0.004 0.044
│ 2019-12-24 15:21:37,701 58 INFO ? werkzeug: 127.0.0.1 - - [24/Dec/2019 15:21:37] "GET / HTTP/1.1" 200 - 1 0.003 0.040
│ 2019-12-24 15:21:47,712 58 INFO ? werkzeug: 127.0.0.1 - - [24/Dec/2019 15:21:47] "GET / HTTP/1.1" 200 - 1 0.003 0.050
│ 2019-12-24 15:21:53,469 58 ERROR bitnami_odoo odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
│ ERROR: relation "ir_module_module" does not exist
│ LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
```

**Comment by carrodher** [comment]
I am not able to reproduce the issue installing it from scratch, are you using a volume or database which contains a lot of data?

**Comment by masterkain** [comment]
you can see here https://github.com/bitnami/bitnami-docker-odoo/issues/76#issuecomment-565965410 the persistence values: for postgres it's an EBS volume, for odoo it's EFS (which is NFS on AWS)

I currently don't have issues with EFS, I mention this because EFS works in a particular way: one needs to have some data volume on there or the service will run slow.

**Comment by carrodher** [comment]
Has the issue happened again? I am trying to reproduce it, but without luck.
Just to summarize, can you confirm if the initial issue related to `odoo-server.conf` is solved? If yes, now we are talking about the slow startup time and that is the issue I am trying to reproduce.
I want to confirm that it was not something transient or because of the first deploy with a huge amount of data or something like that.

**Comment by masterkain** [comment]
hello,
today odoo won't start at all, yes, the issue with the config file has been solved but the slow start up is there.

the user claims he was using odoo via its web interface and suddenly got a 503 and I'm not sure what exactly he did, however odoo won't start, stuck at Initializing odoo.

I have no other clue beside some logs in postgres. I don't think there's much data in database.

![Screenshot 2019-12-31 at 11 46 09](https://user-images.githubusercontent.com/12844/71619130-31a90900-2bc3-11ea-80ed-869d7103a7ad.png)
![Screenshot 2019-12-31 at 11 47 11](https://user-images.githubusercontent.com/12844/71619161-5309f500-2bc3-11ea-8f7e-c4ded3f76e32.png)
![Screenshot 2019-12-31 at 11 47 21](https://user-images.githubusercontent.com/12844/71619165-54d3b880-2bc3-11ea-8d02-7f559536c817.png)

**Comment by juan131** [comment]
Hi @masterkain 

According to [#76 (comment)](https://github.com/bitnami/bitnami-docker-odoo/issues/76#issuecomment-565965410) you were using the `12.0.3` version of the chart.

```yaml
  chart:
    repository: https://charts.bitnami.com
    name: odoo
    version: 12.0.3
```

That version of the chart uses the `12.0.20191115` version of the docker image, while you're using the `12.0.20191215` version in the `12.0.5` version of the chart. There could be some incompatibility between the latest version and your existing data.

Could you please that the issue doesn't appear when you deploy a new Odoo deployment (from scratch)?
