### ISSUE TITLE
ImportError: No module named _renderPM

### ISSUE THREAD

**Issue by frnodb** [bitnami/bitnami-docker-odoo#91]
I have installed odoo-14.0.14 chart. 
Reports with barcodes gives this error:

```Traceback (most recent call last):
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/bitnami/odoo/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/bitnami/odoo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/bitnami/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/bitnami/odoo/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/bitnami/odoo/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/bitnami/odoo/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/opt/bitnami/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/bitnami/odoo/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/bitnami/odoo/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/bitnami/odoo/odoo/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_http.py", line 238, in _dispatch
    return cls._handle_exception(e)
  File "/opt/bitnami/odoo/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/opt/bitnami/odoo/odoo/addons/http_routing/models/ir_http.py", line 610, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_http.py", line 206, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/bitnami/odoo/odoo/http.py", line 750, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/opt/bitnami/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/odoo/addons/web/controllers/main.py", line 1994, in report_barcode
    height=height, humanreadable=humanreadable, quiet=quiet)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_actions_report.py", line 512, in barcode
    return barcode.asString('png')
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/reportlab/graphics/shapes.py", line 852, in asString
    from reportlab.graphics import renderPM
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/reportlab/graphics/renderPM.py", line 33, in <module>
    https://pairlist2.pair.net/mailman/listinfo/reportlab-users""")
ImportError: No module named _renderPM
it may be badly or not installed!
You may need to install development tools
or seek advice at the users list see
https://pairlist2.pair.net/mailman/listinfo/reportlab-users - - -```

**Comment by andresbono** [comment]
Hi @frnodb, how are you activating the reports with barcodes?

The error message shows that `renderPM` module can't be found. Could you exec into the odoo container and execute the following command?

```
/opt/bitnami/odoo/venv/bin/pip install --upgrade --force-reinstall reportlab
```

Then try again to see if the issue is solved.

---

<details>
  <summary>Details (click to expand)</summary>

At least, for us it worked that way:

```
$ docker run --rm -it bitnami/odoo:13.0.20200810-debian-10-r5 bash
```
```
$ /opt/bitnami/odoo/venv/bin/python
Python 3.6.12 (default, Aug 20 2020, 13:54:41)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from reportlab.graphics import renderPM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bitnami/odoo/venv/lib/python3.6/site-packages/reportlab/graphics/renderPM.py", line 33, in <module>
    https://pairlist2.pair.net/mailman/listinfo/reportlab-users""")
ImportError: No module named _renderPM
it may be badly or not installed!
You may need to install development tools
or seek advice at the users list see
https://pairlist2.pair.net/mailman/listinfo/reportlab-users
```
```
$ /opt/bitnami/odoo/venv/bin/pip install --upgrade --force-reinstall reportlab
Collecting reportlab
  Downloading reportlab-3.5.48-cp36-cp36m-manylinux2010_x86_64.whl (2.6 MB)
     |################################| 2.6 MB 11.0 MB/s
Collecting pillow>=4.0.0
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
     |################################| 2.2 MB 66.9 MB/s
Installing collected packages: pillow, reportlab
  Attempting uninstall: pillow
    Found existing installation: Pillow 5.4.1
    Uninstalling Pillow-5.4.1:
      Successfully uninstalled Pillow-5.4.1
  Attempting uninstall: reportlab
    Found existing installation: reportlab 3.5.13
    Uninstalling reportlab-3.5.13:
      Successfully uninstalled reportlab-3.5.13
Successfully installed pillow-7.2.0 reportlab-3.5.48
```
```
$ /opt/bitnami/odoo/venv/bin/python
Python 3.6.12 (default, Aug 20 2020, 13:54:41)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from reportlab.graphics import renderPM
>>>
```

`reportlab` was updated from `3.5.13` to `3.5.48`, even though the _requirements.txt_ of Odoo specifies the older: https://github.com/odoo/odoo/blob/13.0/requirements.txt#L39

</details>

**Comment by frnodb** [comment]
It worked!!
Thanks!

**Comment by andresbono** [comment]
That's great to hear, @frnodb! Please note that you might need to execute the command again if the container is restarted. To solve it, you may want to create your own container image and use it in the chart:

```
FROM bitnami/odoo:13-debian-10
RUN /opt/bitnami/odoo/venv/bin/pip install --upgrade --force-reinstall reportlab
```
